clean up

diff --git a/.github/workflows/publish_testpypi.yaml b/.github/workflows/publish_testpypi.yaml
--- a/.github/workflows/publish_testpypi.yaml
+++ b/.github/workflows/publish_testpypi.yaml
@@ -8,43 +8,39 @@ on:
       - 'dev'
 
 jobs:
-  # deploy_testpypi:
-  #   runs-on: ubuntu-latest
-  #   steps:
-  #   - uses: actions/checkout@v3
-  #     with:
-  #       fetch-depth: 0  # Required for full commit history check
-  #   - name: Verify tag is on dev branch
-  #     run: |
-  #       TAG_NAME=${GITHUB_REF#refs/tags/}
-  #       COMMIT=$(git rev-parse $TAG_NAME)
-  #       if ! git branch --contains $COMMIT | grep -qw dev; then
-  #         echo "::error::Tag $TAG_NAME must be created from dev branch"
-  #         exit 1
-  #       fi
-  #   - name: Set up Python
-  #     uses: actions/setup-python@v4
-  #     with:
-  #       python-version: '3.x'
-  #   - name: Install dependencies
-  #     run: |
-  #       python -m pip install --upgrade pip
-  #       pip install build twine
-  #   - name: Build and publish
-  #     env:
-  #       #TWINE_USERNAME: ${{ secrets.TEST_PYPI_USERNAME }}
-  #       TWINE_USERNAME: __token__
-  #       #TWINE_PASSWORD: ${{ secrets.TEST_PYPI_PASSWORD }}
-  #       TWINE_PASSWORD: pypi-AgENdGVzdC5weXBpLm9yZwIkNDZiZWNmYTktNzc0Ni00MmY4LWFmMzMtNWEwMzZkZDZmNjg0AAIqWzMsIjYxMDVkNDhmLWMyOWItNDUyMC1iOTk3LTVmOWRlYjA0ZWE2OCJdAAAGIGsKd-6cZogx2uYdT1Lho8OzAVNtGbpvfgBQNsK3dIb3
-  #       ACTIONS_STEP_DEBUG: true
-  #     run: |
-  #       echo "TWINE_USERNAME  is set to $TWINE_USERNAME"
-  #       echo "TWINE_PASSWORD is set to: ${TWINE_PASSWORD}"
-  #       echo "TWINE_PASSWORD  is set to: $TWINE_PASSWORD"
-  #       echo "TWINE_PASSWORD first 5 chars: ${TWINE_PASSWORD:0:184}"
-  #       echo "TWINE_PASSWORD length: ${#TWINE_PASSWORD}"
-  #       python -m build
-  #       twine upload --verbose --repository-url https://test.pypi.org/legacy/ dist/*
+  deploy_testpypi:
+    runs-on: ubuntu-latest
+    steps:
+    - uses: actions/checkout@v3
+      with:
+        fetch-depth: 0  # Required for full commit history check
+    - name: Verify tag is on dev branch
+      run: |
+        TAG_NAME=${GITHUB_REF#refs/tags/}
+        COMMIT=$(git rev-parse $TAG_NAME)
+        if ! git branch --contains $COMMIT | grep -qw dev; then
+          echo "::error::Tag $TAG_NAME must be created from dev branch"
+          exit 1
+        fi
+    - name: Set up Python
+      uses: actions/setup-python@v4
+      with:
+        python-version: '3.x'
+    - name: Install dependencies
+      run: |
+        python -m pip install --upgrade pip
+        pip install build twine
+    - name: Build and publish
+      env:
+        #TWINE_USERNAME: ${{ secrets.TEST_PYPI_USERNAME }}
+        TWINE_USERNAME: __token__
+        TWINE_PASSWORD: ${{ secrets.TEST_PYPI_PASSWORD }}
+        #ACTIONS_STEP_DEBUG: true
+      run: |
+        # echo "TWINE_PASSWORD first 5 chars: ${TWINE_PASSWORD:0:184}"
+        # echo "TWINE_PASSWORD length: ${#TWINE_PASSWORD}"
+        python -m build
+        twine upload --verbose --repository-url https://test.pypi.org/legacy/ dist/*
 
   test-colab:
     #needs: deploy_testpypi
